//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OroPuroWEB.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Prod_OroPuroEntities : DbContext
    {
        public Prod_OroPuroEntities()
            : base("name=Prod_OroPuroEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<IMF_SP_Ventas_Result> IMF_SP_Ventas(Nullable<System.DateTime> fecha_inicial, Nullable<System.DateTime> fecha_final, string ruta, string tipo_tienda, string tipo_presentacion, string agupar)
        {
            var fecha_inicialParameter = fecha_inicial.HasValue ?
                new ObjectParameter("fecha_inicial", fecha_inicial) :
                new ObjectParameter("fecha_inicial", typeof(System.DateTime));
    
            var fecha_finalParameter = fecha_final.HasValue ?
                new ObjectParameter("fecha_final", fecha_final) :
                new ObjectParameter("fecha_final", typeof(System.DateTime));
    
            var rutaParameter = ruta != null ?
                new ObjectParameter("ruta", ruta) :
                new ObjectParameter("ruta", typeof(string));
    
            var tipo_tiendaParameter = tipo_tienda != null ?
                new ObjectParameter("tipo_tienda", tipo_tienda) :
                new ObjectParameter("tipo_tienda", typeof(string));
    
            var tipo_presentacionParameter = tipo_presentacion != null ?
                new ObjectParameter("tipo_presentacion", tipo_presentacion) :
                new ObjectParameter("tipo_presentacion", typeof(string));
    
            var aguparParameter = agupar != null ?
                new ObjectParameter("agupar", agupar) :
                new ObjectParameter("agupar", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IMF_SP_Ventas_Result>("IMF_SP_Ventas", fecha_inicialParameter, fecha_finalParameter, rutaParameter, tipo_tiendaParameter, tipo_presentacionParameter, aguparParameter);
        }
    
        public virtual ObjectResult<SBO_SP_IMF_LoginWeb_Result> SBO_SP_IMF_LoginWeb(string user, string password)
        {
            var userParameter = user != null ?
                new ObjectParameter("User", user) :
                new ObjectParameter("User", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SBO_SP_IMF_LoginWeb_Result>("SBO_SP_IMF_LoginWeb", userParameter, passwordParameter);
        }
    }
}
